 ### Scaler標準化。 
 ### MinMaxScaler將屬性縮放到 0~1
 ### StandardScaler保存訓練集中的參數（均值、標準差）直接使用其對象轉換測試集數據。

In [1]:
from sklearn.preprocessing import MinMaxScaler 

In [2]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

### 此範例操作 要模仿的部分:MinMaxScaler

In [3]:
scaler = MinMaxScaler() 

In [4]:
#----fit----
scaler.fit(data)   

MinMaxScaler(copy=True, feature_range=(0, 1))

In [5]:
# data_max_  
scaler.data_max_  

array([ 1., 18.])

In [6]:
# data_min_
scaler.data_min_ 

array([-1.,  2.])

In [7]:
#----transform----
scaler.transform(data) 

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [8]:
scaler.transform([[2,2]]) 

array([[1.5, 0. ]])

In [9]:
import numpy as np

### 模擬
### 試算類別中的 fit、transform，找出原計算方式

In [10]:
# fit--找scaler.data_max_的原理
np.max(data, axis=0)

array([ 1., 18.])

In [11]:
#  fit--找scaler.data_min_的原理
np.min(data, axis=0)

array([-1.,  2.])

In [12]:
# transform--找scaler.transform的原理調。 整成 0~1之間
(np.array(data) - scaler.data_min_) / (scaler.data_max_ - scaler.data_min_)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [13]:
 class MyMinMaxScaler: # 【　MyMinMaxScaler 此類別有以下功能　】 還有更多功能　
    
    def __init__(self):                             #初始化定義
        self.data_max_ = None
        self.data_min_ = None
        
    def fit(self,data):                            #self:慣例上，第一個傳self  #第二個傳data
        self.data_max_ = np.max(data, axis=0)
        self.data_min_ = np.min(data, axis=0)
        
    def transform(self,data):
        return (np.array(data) - self.data_min_) / (self.data_max_ - self.data_min_)
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

### 測試模擬結果

In [14]:
myscaler = MyMinMaxScaler()

In [15]:
myscaler.fit(data)   

In [16]:
myscaler.data_max_

array([ 1., 18.])

In [17]:
myscaler.data_min_

array([-1.,  2.])

In [18]:
myscaler.transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [19]:
myscaler.transform([[2,2]])

array([[1.5, 0. ]])